use_frameworks!

platform :ios, '8.0'

target 'Track_Example' do
  pod 'Track', :path => '../'
  pod 'Masonry'
  target 'Track_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
